# Generated by Django 4.2.13 on 2024-05-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lyric',
            options={'ordering': ['-created_on']},
        ),
    ]
