# Generated by Django 4.2.13 on 2024-05-25 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0004_alter_lyric_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
