# Generated by Django 4.2.13 on 2024-05-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0007_lyric_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Submitted')], default=0),
        ),
    ]
