# Generated by Django 4.2.13 on 2024-05-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0008_alter_lyric_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
