# Generated by Django 4.2.13 on 2024-05-30 02:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lyrics', '0012_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='lyric_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
